import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ffffff',
  },
  contentContainer: {
    width: '100%',
    height: 270,
    justifyContent: 'space-between',
  },
  paginationBoxStyle: {
    bottom: 0,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    position: 'absolute',
  },
  headerimage: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  child: {
    width: '100%',
    height: '100%',
    position: 'relative',
    justifyContent: 'center',
  },
  buttonContainer: {
    paddingHorizontal: 10,
    marginTop: '30%',
    margin: 10,
    zIndex: 1,
  },
  contaisliderbox: {
    width: 337,
    alignItems: 'center',
    justifyContent: 'center',
    height: 270,
    flexDirection: 'row',
    position: 'absolute',
    marginEnd: 4,
  },
  buttonIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  contaibutontree: {
    width: '100%',
    height: 58,
  },
  contentbuttontree: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 48,
    paddingVertical: 15,
    gap: 10,
    alignSelf: 'stretch',
  },
  bottontree: {
    width: 'auto',
    height: 40,
    borderRadius: 10,
    backgroundColor: '#009245',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  textbuttontree: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    lineHeight: 22,
  },
  contentext: {
    width: '100%',
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 17,
    alignSelf: 'stretch',
  },
  mony: {
    width: 279,
    height: 34,
    fontSize: 24,
    fontWeight: '500',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#007537',
  },
  contenchitiet: {
    width: '100%',
    height: 173,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 17,
    paddingHorizontal: 40,
    paddingVertical: 48,
    alignSelf: 'stretch',
  },
  textchitiet: {
    width: 'auto',
    height: 'auto',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#3a3a3a',
    lineHeight: 22,
  },
  contaichitiet: {
    width: 279,
    height: 'auto',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignSelf: 'stretch',
  },
  textkc: {
    width: 'auto',
    height: 'auto',
    lineHeight: 20,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#3a3a3a',
  },
  textsp: {
    width: 'auto',
    height: 'auto',
    lineHeight: 20,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#007537',
  },
  contaifooter: {
    width: '100%',
    height: 'auto',
    paddingTop: 0,
    paddingHorizontal: 24,
    paddingBottom: 15,

    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contaitamtinh: {
    width: '100%',
    height: 82,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 2,
    paddingVertical: 15,
    alignSelf: 'stretch',
  },
  texttamtinh: {
    width: 92,
    textAlign: 'right',
    height: 'auto',
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#000',
    lineHeight: 20,
  },
  contaitientamtinh: {
    height: 36,
    flexDirection: 'column',
    display: 'flex',
    justifyContent: 'center',
    flexShrink: 0,
    alignSelf: 'stretch',
  },
  tientamtinh: {
    width: 92,
    height: 36,
    fontSize: 24,
    fontWeight: '500',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#000',
    lineHeight: 34,
    textAlign: 'right',
  },
  textspdachon: {
    width: 'auto',
    height: 'auto',
    lineHeight: 20,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#000',
  },
  contaisquare: {
    width: 'auto',
    height: 'auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
    flexDirection: 'row',
  },
  iconsquare: {
    width: 30,
    height: 30,
    flexShrink: 0,
  },
  contaitextsquare: {
    display: 'flex',
    width: 8,
    height: 30,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  textsquare: {
    lineHeight: 20,
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: '#000',
    textAlign: 'center',
  },
  contaibuttonchonmua: {
    width: '100%',
    display: 'flex',
    height: 50,
    paddingVertical: 10,
    paddingHorizontal: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ABABAB',
    borderRadius: 10,
    alignSelf: 'stretch',
  },
  buttonchonmua: {
    width: '100%',
    height: 'auto',
    backgroundColor: '#ABABAB',
    borderRadius: 10,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textchonmua: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    color: 'white',
    lineHeight: 22,
    textTransform: 'uppercase',
  },
  emptyText: {
    width: 0,
    height: 0,
  },
});
